apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- digest: sha256:7d8a40f704a18986a50a9b958beba7c860b794c2d88b6857528cb3a4f8d947ff
  name: app1
  newName: 460665430878.dkr.ecr.us-east-1.amazonaws.com/app1-staging
