apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- digest: sha256:b07c3c9600ee1d5220a3c3d26fba7391dca7db1ac938214f65e3a9265301540b
  name: app1
  newName: 460665430878.dkr.ecr.us-east-1.amazonaws.com/app1-staging
