apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- digest: sha256:a5a2766e16df99200d86fe8a4d6c2c363e91940b2b30467f5a06d039e26560be
  name: app1
  newName: 460665430878.dkr.ecr.us-east-1.amazonaws.com/app1-staging
