apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- digest: sha256:d805b7266612259e3f45edee223065cc4b3758c17a40cdfd44e9cd7e54e3e7d6
  name: app2
  newName: 460665430878.dkr.ecr.us-east-1.amazonaws.com/app2-staging
