apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- digest: sha256:528fae678b675eae389a4b00c97479f8fcd86a7a1fcbcfe978b024db352dce1c
  name: app2
  newName: 460665430878.dkr.ecr.us-east-1.amazonaws.com/app2-staging
