apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- digest: sha256:6e1eb00f03f5c2650d5efe750edc84251617bac83c022a069d3ae7afdb9b619c
  name: app1
  newName: 460665430878.dkr.ecr.us-east-1.amazonaws.com/app1-production
