apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- digest: sha256:2656b9d6f5d57343e12cfdd1099bc91a970cc41c0a3eed55f35134a8fb3a9e62
  name: app1
  newName: 460665430878.dkr.ecr.us-east-1.amazonaws.com/app1-production
