name: build

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        foo: ["bar", "bad"]

    steps:
      - run: echo ${{ matrix.foo }} - ${{ github.sha }}
      - if: ${{ matrix.foo == 'baz' }}
        run: exit 1

  test-success:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: test

    steps:
      - if: ${{ needs.test.result == 'failure' }}
        run: exit 1

  publish-staging:
    runs-on: ubuntu-latest
    needs: test-success

    steps:
      - run: echo "Publishing to staging - ${{ github.sha }}"



