name: publish

on:
  release:
    types: [published]


jobs:

  publish-production:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Publishing to production - ${{ github.sha }} - ${{ github.event.release.tag_name }}"


  update:
    runs-on: ubuntu-latest
    needs: publish-production

    steps:
      - run: echo "Updating things after publish - ${{ github.sha }} - ${{ github.event.release.tag_name }}"