name: publish

on:
  release:
    types:
      - released


jobs:

  publish-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
        echo "Publishing to production - ${{ github.sha }} - ${{ github.event.release.tag_name }}"
        ls


  update:
    runs-on: ubuntu-latest
    needs: publish-production

    steps:
      - run: echo "Updating things after publish - ${{ github.sha }} - ${{ github.event.release.tag_name }}"